# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "group-project"
    dynamodb_table = "group-project-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
  }
}
