name: Terraform plan and apply
on: 
    workflow_dispatch:
    push:
        branches:
              - main

    pull_request:
        branches:
              - main
            #- test - This is to show that multiple branches can be targeted for a specific event trigger
            #- dev
            #- sandbox

env: 
  TERRAFORM_VERSION: 1.7.2
  TERRAGRUNT_VERSION: 0.56.0
  TERRAFORM_WORKING_DIR:  "./applied/Prod"    
  

permissions:
      contents: write
      pull-requests: read  
      issues: write

concurrency: revolution # this will ensure only a single workflow is run at a time

jobs:
    plan:
        name: "Terragrunt Init, Validate and Plan"
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-24.04 
        defaults:
          run:
            working-directory: ${{env.TERRAFORM_WORKING_DIR}}
        steps:
              - name : "Checkout"
                uses: actions/checkout@v4
                with:
                    ref: ${{github.event.pull_request.head.ref}}

              - name : Install Terraform
                uses: hashicorp/setup-terraform@v3
                with:
                  terraform_version: ${{env.TERRAFORM_VERSION}}
                  terraform_wrapper: true

              - name : Install Terragrunt
                uses: autero1/action-terragrunt@v3
                with:
                 terragrunt-version: ${{env.TERRAGRUNT_VERSION}}
              
              - name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
                env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

              - name: Terragrunt init
                id: init
                run: terragrunt run-all init -no-color --terragrunt-non-interactive

              - name: Terragrunt Validate
                id: validate
                run: terragrunt run-all validate -no-color --terragrunt-non-interactive

              - name: Terragrunt Plan
                id: Plan
                run: terragrunt run-all Plan -no-color --terragrunt-non-interactive 
                continue-on-error: true
    apply:
      name: "Terragrunt Apply"  
      if: github.event_name == 'Push'
      runs-on: ubuntu-24.04 
      defaults:
        run:
          working-directory: ${{env.TERRAFORM_WORKING_DIR}}
      steps:
              - name : "Checkout"
                uses: actions/checkout@v4
                with:
                  ref: ${{github.event.pull_request.head.ref}}
              - name : Install Terraform
                uses: hashicorp/setup-terraform@v3
                with:
                   terraform_version: ${{env.TERRAFORM_VERSION}}
                   terraform_wrapper: true

              - name : Install Terragrunt
                uses: autero1/action-terragrunt@v3
                with:
                 terragrunt_version: ${{env.TERRAGRUNT_VERSION}}
        
              - name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: us-east-1
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

              - name: Terragrunt init
                id: init
                run: terragrunt run-all init -no-color --terragrunt-non-interactive

              - name: Terragrunt Apply
                id: apply
                run: terragrunt run-all apply -no-color --terragrunt-non-interactive 
                continue-on-error: true         
                  


  