name: Terraform plan and apply

on: 
    workflow_dispatch:
    #push:
        #branches:
         #- main

    pull_request:
        branches:
          - main
          #- test - This is to show that multiple branches can be targeted for a specific event trigger
          #- dev
          #- sandbox


permissions:
      contents: write
      pull-requests: read  
      issues: write

concurrency: revolution # this will ensure only a single workflow is run at a time

jobs:
  kics:
      name: Run KICS code Analysis
      runs-on: ubuntu-24.04
      steps:
      - name: checkout
        uses : actions/checkout@v3
        with:
         ref: ${{github.event.pull_request.head.ref}}
          
      - name:  Run kICS Scan
        uses : checkmarx/kics-github-action@v2.0.0
        with:
          path: ./infrastructure/region/iam_group
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
          ignore_on_exit: results
          enable_comments: true

      - name: display kics results
        run: |
          cat myResults/results.json


  run_plan_dev_environment:
      name: dev-enviroment terraform plan
      needs: [kics]
      uses: ./.github/workflows/reuseable_plan_actions.yml
      with: 
        #ENVIRONMENT_NAME: "dev"
        TERRAFORM_WORKING_DIR:  "./applied/Prod"
        TERRAFORM_VERSION: "1.7.2"
        TERRAGRUNT_VERSION: "0.58.0"
        AWS_REGION: "us-east-1"
      secrets: inherit

  run_apply_in_dev_environment:
      name: dev-environment terraform apply
      needs: [run_plan_dev_environment]
      uses: ./.github/workflows/reuseable_apply_actions.yml
      with: 
        #ENVIRONMENT_NAME: "dev"
        TERRAFORM_WORKING_DIR:  "./applied/Prod"
        TERRAFORM_VERSION: "1.7.2"
        TERRAGRUNT_VERSION: "0.58.0"
        AWS_REGION: "us-east-1"
      secrets: inherit

  run_plan_in_Prod_environment:
     name: Prod-environment terraform plan
     needs: [run_apply_in_dev_environment]
     uses: ./.github/workflows/reuseable_plan_actions.yml
     with: 
       #ENVIRONMENT_NAME: "Prod"
       TERRAFORM_WORKING_DIR:  "./applied/Prod"
       TERRAFORM_VERSION: "1.7.2"
       TERRAGRUNT_VERSION: "0.58.0"
       AWS_REGION: "us-east-1"
     secrets: inherit

  run_apply_in_Prod_environment:
     name: Prod-environment terraform apply
     needs: [run_plan_in_Prod_environment]
     uses: ./.github/workflows/reuseable_apply_actions.yml
     with: 
       #ENVIRONMENT_NAME: "Prod"
       TERRAFORM_WORKING_DIR:  "./applied/Prod"
       TERRAFORM_VERSION: "1.7.2"
       TERRAGRUNT_VERSION: "0.58.0"
       AWS_REGION: "us-east-1"
     secrets: inherit
  
    
                  


  