# run on call from another workflow

on:
    workflow_call:
         Inputs:
              TERRAFORM_VERSION: 1.7.2
                  description: "terraform version to be run on runner"
                  required: true
                  type: string
              TERRAGRUNT_VERSION: 0.58.0
                  description: "Terragrunt version to be installed on runner"
                  required: true
                  type: string
              TERRAFORM_WORKING_DIR:
                  DESCRIPTION: "Path to the terraform configuration"
                  required: true
                  type: string
              AWS_REGION:
                 required: true
                 type: string
              ENVIROMENT_NAME:
                  required: true
                  type: string

    apply:
        name: "Terragrunt Apply"  
        environment: ${{inputs.ENVIRONMENT_NAME}}
        if: github.event_name == 'Push'
        runs-on: ubuntu-24.04 
        defaults:
          run:
            working-directory: ${{env.TERRAFORM_WORKING_DIR}}
        steps:
                - name : "Checkout"
                  uses: actions/checkout@v4
                  with:
                    ref: ${{github.event.pull_request.head.ref}}
                - name : Install Terraform
                  uses: hashicorp/setup-terraform@v3
                  with:
                     terraform-version: ${{inputs.TERRAFORM_VERSION}}
                     terraform_wrapper: true
              
                - name : Install Terragrunt
                  uses: autero1/action-terragrunt@v3
                  with:
                   terragrunt-version: ${{inputs.TERRAGRUNT_VERSION}}
                      
                - name: Configure AWS Credentials
                  uses: aws-actions/configure-aws-credentials@v4
                  with:
                   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                   aws-region: ${{inputs.AWS_REGION}}
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
              
                - name: Terragrunt init
                  id: init
                  run: terragrunt run-all init -no-color --terragrunt-non-interactive
              
                - name: Terragrunt Apply
                  id: apply
                  run: terragrunt run-all apply -no-color --terragrunt-non-interactive 
                  continue-on-error: true    

                - name: Terragrunt Destroy
                  id: destroy
                  run: terragrunt run-all destroy -no-color --terragrunt-non-interactive 
                  continue-on-error: true  

